name: Build and Test Ubuntu 16.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código no repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build da imagem Docker baseada no Ubuntu 16.04
      - name: Build Docker image
        run: |
          docker build -t my-ubuntu16-image .
      
      # Rodar comandos ou testes dentro da imagem
      - name: Run inside Docker container
        run: |
          docker run my-ubuntu16-image bash -c "lsb_release -a && echo 'Ubuntu 16.04 configurado!'"
